In [30]:
import numpy as np

In [9]:
# 1
a = np.matrix ("1, 1, 1; 0.05, 0.07, 0; 0.05, 0, 0.06")
b = np.matrix ("50000; 2250; 1400")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)

[[10000.]
 [25000.]
 [15000.]]


In [10]:
# 2
a = np.matrix ("1,1,1;1,-1,0;1,0,-1")
b = np.matrix ("1328;-120;100")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)

[[436.]
 [556.]
 [336.]]


In [20]:
# 3
A = np.matrix ("3,0,3;6,0.25,0;1,(0.3),1")
B = np.matrix ("1;1;1")
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print(1/X)

[[13.5       ]
 [ 0.45      ]
 [ 3.85714286]]


In [22]:
# 4
a = np.matrix ("1,1,1;9,3,1;1,-1,1")
b = np.matrix("12;54;2")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)

[[4.]
 [5.]
 [3.]]


In [28]:
# 5
def get_polynom(coords):
    a_matr = ''
    b_matr = ''
    for point in coords:
        x = point[0]
        y = point[1]
        a_matr += ','.join([f'{x*x}', f'{x}', '1'])+';'
        b_matr += f'{y}' + ';'
    a = np.matrix(a_matr.rstrip(';'))
    b = np.matrix(b_matr.rstrip(';'))
    return np.linalg.solve (a,b)

coords = [(1,12), (3,54), (-1,2)]
print(get_polynom(coords))

[[4.]
 [5.]
 [3.]]
